version: "3"
services:
  web: 
    container_name: tpi_python1
    build: ./tpi_python/www
    restart: always
    ports:
      - "15000:5000"
    env_file:
      - ./tpi_python/config/.env
    depends_on:
      - db
    volumes:
      - ./tpi_python/www/app.py:/www/app.py:ro
      - ./tpi_python/www/database.py:/www/database.py:ro
      - ./tpi_python/www/templates:/www/templates:ro

  db:
    container_name: mysqldb-tpi
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "wally"
      MYSQL_USER: "example"
      MYSQL_PASSWORD: "example"
    volumes:
      - ./tpi_python/database/wally.sql:/docker-entrypoint-initdb.d/wally.sql:ro
